.PHONY: clean All

All:
	@echo "----------Building project:[ Substitution_Cipher - Debug ]----------"
	@cd "Arrays" && "$(MAKE)" -f  "Substitution_Cipher.mk"
clean:
	@echo "----------Cleaning project:[ Substitution_Cipher - Debug ]----------"
	@cd "Arrays" && "$(MAKE)" -f  "Substitution_Cipher.mk" clean
