.PHONY: clean All

All:
	@echo "----------Building project:[ TextTree - Debug ]----------"
	@cd "TextTree" && "$(MAKE)" -f  "TextTree.mk"
clean:
	@echo "----------Cleaning project:[ TextTree - Debug ]----------"
	@cd "TextTree" && "$(MAKE)" -f  "TextTree.mk" clean
