.PHONY: clean All

All:
	@echo "----------Building project:[ PointersSectionChallenge - Debug ]----------"
	@cd "PointersSectionChallenge" && "$(MAKE)" -f  "PointersSectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ PointersSectionChallenge - Debug ]----------"
	@cd "PointersSectionChallenge" && "$(MAKE)" -f  "PointersSectionChallenge.mk" clean
